### ISSUE TITLE
Section Member

### ISSUE THREAD

**Issue by hawariMuflihMunte** [uniicode-id/uniicode-landing-next#1]
Pengerjaan fitur `<section-member>`

**Comment by hawariMuflihMunte** [comment]
Izin bertanya, pada proyek ini dikatakan bahwa sebelum melakukan pull request, dianjurkan untuk menjalankan **Prettier** terlebih dahulu agar kode terformat sesuai dengan konfigurasi yang telah ditentukan. Masalahnya, saat saya ingin menjalankan **Prettier**, **Prettier** tersebut tidak ada pada proyek. Saya ingin mengetahui kelanjutan dari permasalahan ini.

@dimar-hanung @NoxturneDev

**Comment by dimar-hanung** [comment]
langsung format aja pakai extension prettier di code editor yang dipakai bisa, udah ada `.prettierrc` nya di project jadi harusnya udah otomotasi ngikutin konfigurasi project

**Comment by dimar-hanung** [comment]
> Izin bertanya, pada proyek ini dikatakan bahwa sebelum melakukan pull request, dianjurkan untuk menjalankan **Prettier** terlebih dahulu agar kode terformat sesuai dengan konfigurasi yang telah ditentukan. Masalahnya, saat saya ingin menjalankan **Prettier**, **Prettier** tersebut tidak ada pada proyek. Saya ingin mengetahui kelanjutan dari permasalahan ini.
> 
> @dimar-hanung @NoxturneDev

langsung format aja pakai extension prettier di code editor yang dipakai bisa, udah ada .prettierrc nya di project jadi harusnya udah otomotasi ngikutin konfigurasi project @hawariMuflihMunte

**Comment by hawariMuflihMunte** [comment]
Oke siap, berarti settingan prettier di sesuaikan dengan extension code editor ya.

Lanjut kerja 😁

Terimakasih banyak atas responnya.
